services:

  taisaovayem:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3000:3000
    environment:
      VERCEL_PROJECT_PRODUCTION_URL: taisaovayem.com
      FACEBOOK_APP_ID: "541539815528484"
      API: https://admin.taisaovayem.com/wp-json/wp/v2

